### ISSUE TITLE
repeated consumption

### ISSUE THREAD

**Issue by cshuig** [RTBHOUSE/kafka-workers#19]
If the current consumer's offset state is: 1, 2, 3, 5, 6, 7 are processed, 4 comsumed, then the consumer rebalancing, only submit 1, 2, 3； when after balancing, consumer pull message from offset = 4 began to consume, 5, 6, 7 repeated consumption

current consumer offset state： 1、2、3、5、6、7   processed
trigger rebalance
commitSync offset：1、2、3
after balancing
consumer from offset=4 
5、6、7 is repeated consumption

**Comment by barteklos** [comment]
Thank you for your issue and sorry for late answer. I would like to understand your scenario better. 

As I understand you fully processed records with offsets 1, 2, 3, 5, 6, 7 but not 4 (observer's method onSuccess() was not called for record with offset 4)? If it is your case (maybe because of asynchronous processing or subpartitioning?) it is correct in terms of kafka-workers design.

Indeed, kafka-workers supports at-least-once semantics and commits only continuously processed offsets. We could not commit 5, 6 or 7 until 4 was not fully processed (could not be committed) because than it could lead to data loss.

Of course it could lead to repeated consumption (or duplicates) and because of that we deduplicate events at the end (on output component side). The way to minimalize duplicates is to call onSuccess() method for every processed record (it could be done in task's close() method as well) and than these offsets will be committed before partition rebalance but only if there are no gaps.

**Comment by cshuig** [comment]
I have an idea. When triggering rebalancing, you can put 4 into a separate queue, then change the 4 state to processed, then commit offset=6, and there is a separate thread in the local to consume 4 and process. Here we need to record the current maximum size of the partition.

I'm not good at English.

**Comment by bdamian** [comment]
In case of rebalance an additional queue is enough. But imagine a scenario with application failure. The queue, or more general – an external storage, is needed to preserve the information that messages at offsets 5, 6, 7 were processed, but not yet commited. On other hand, if a message is processed successfully, then you should call `onSuccess` on appropriate `RecordStatusObserver`. Then, with some delay offsets are commited to Kafka. If the delay is too long for you, try to tune your configuration, check `consumer.commit.interval.ms` option.
